from typing import Tuple, List, Any
import numpy as np

Point = Tuple[float, float, float]
Mat4x4d = List[List[float]]

class AABB:
    def __init__(self, v0: Point, v1: Point) -> None: ...
    @property
    def v0(self) -> np.ndarray: ...
    @property
    def v1(self) -> np.ndarray: ...

class OcclusionBuffer:
    def __init__(self, w: int, h: int) -> None: ...
    def get(self, x: int, y: int) -> Any: ...

class OcclusionCuller:
    def __init__(self, proj: Mat4x4d, shape: Tuple[int, int]) -> None: ...
    def write(self, aabb: AABB) -> None: ...
    def test(self, aabb: AABB) -> bool: ...

def rasterize_aabb_inclusive(aabb: AABB) -> Any: ...
def rasterize_aabb_exclusive(aabb: AABB) -> Any: ...
def rasterize_many_aabb_inclusive(aabbs: List[AABB]) -> Any: ...
def rasterize_many_aabb_exclusive(aabbs: List[AABB]) -> Any: ...