from typing import Any
import numpy as np

class SimplexNoise:
    def __init__(self, seed: int) -> None: ...
    def noise(self, pos: np.ndarray) -> np.ndarray: ...

def noise(domain: np.ndarray) -> np.ndarray: ...