from typing import Generic, TypeVar, Tuple, Union, Optional, Any
import numpy as np

T = TypeVar('T', bool, int, float)

class Tensor(Generic[T]):
    def __init__(self, shape: Tuple[int, int, int], fill: T = ...) -> None: ...
    def __str__(self) -> str: ...
    def fill(self, fill: T) -> None: ...
    def get(self, x: int, y: int, z: int) -> T: ...
    def assign(self, pos: np.ndarray, val: np.ndarray) -> None: ...
    def dumps(self) -> str: ...
    def loads(self, blob: str) -> None: ...
    def dump(self) -> bytes: ...
    def load(self, blob: str) -> None: ...
    def array(self) -> np.ndarray: ...
    @staticmethod
    def fromarray(array: np.ndarray) -> 'Tensor[T]': ...

Tensor_Bool = Tensor[bool]
Tensor_I8 = Tensor[int]
Tensor_I16 = Tensor[int] 
Tensor_I32 = Tensor[int]
Tensor_I64 = Tensor[int]
Tensor_U8 = Tensor[int]
Tensor_U16 = Tensor[int]
Tensor_U32 = Tensor[int]
Tensor_U64 = Tensor[int]
Tensor_F32 = Tensor[float]
Tensor_F64 = Tensor[float]