from typing import Any

def clear(tensor: Any, mask: Any) -> Any: ...
def slice(tensor: Any, mask: Any) -> Any: ...
def merge(left: Any, right: Any) -> Any: ...
def write(tensor: Any, mask: Any, value: Any) -> Any: ...
