from typing import Any


def from_block_id(arg0: int) -> Any: ...
def from_flora_id(arg0: int) -> Any: ...
def from_glass_id(arg0: int) -> Any: ...
def is_valid_block_id(arg0: int) -> bool: ...
def is_valid_flora_id(arg0: int) -> bool: ...
def is_valid_glass_id(arg0: int) -> bool: ...
def to_blocks(arg0: Any) -> Any: ...
def to_florae(arg0: Any) -> Any: ...
def to_glass(arg0: Any) -> Any: ...
