from typing import Any
import numpy as np

class Transform:
    permute: np.ndarray
    reflect: np.ndarray
    shift: np.ndarray

def apply(tensor: Any, transform: Transform) -> Any: ...
def compose(t1: Transform, t2: Transform) -> Transform: ...
def permute(transform: Transform) -> Transform: ...
def reflect(transform: Transform) -> Transform: ...
def shift(transform: Transform) -> Transform: ...
