from typing import List, Tuple
import numpy as np

class Node:
    def get(self, x: float, y: float) -> float: ...

def make_disk(r: float) -> Node: ...
def make_rect(w: float, h: float) -> Node: ...
def transform(child: Node, t: Tuple[float, float], r: float) -> Node: ...
def union(nodes: List[Node]) -> Node: ...
def rasterize(
    node: Node, shape: Tuple[int, int], threshold: float = 1e-3
) -> np.ndarray: ...
