from typing import List, Tuple
import numpy as np

class Node:
    def get(self, x: float, y: float, z: float) -> float: ...

def make_ball(r: float) -> Node: ...
def make_box(w: float, h: float, d: float) -> Node: ...
def transform(
    child: Node, t: Tuple[float, float, float], r: Tuple[float, float, float, float]
) -> Node: ...
def union(nodes: List[Node]) -> Node: ...
def rasterize(
    node: Node, shape: Tuple[int, int, int], threshold: float = 1e-3
) -> np.ndarray: ...
